### ISSUE TITLE
Exception in 'Variables' view ('Debug' perspective) at first opening

### ISSUE THREAD

**Issue by martianov** [xored/f4#95] opened 2016-07-14 12:07 UTC
![f4_1_0_3-exception-variables-view](https://cloud.githubusercontent.com/assets/9569740/16838418/ced9c02a-49ea-11e6-9350-a030bc1f8660.png)

Steps to reproduce:
0. At empty Workspace:
1. Create new Fantom Project (for example, 'Test')
2. Create new Fantom Class (for example, 'Test')
3. I suppose issue doesn't depends on exact code but you can use code from screenshot: [Test.fan.zip](https://github.com/xored/f4/files/363624/Test.fan.zip)
4. Set breakpoint
5. Run Debug as Fantom class
6. Switch to 'Debug' perspective

Notice:
Sometimes switch between 'Variables' and any other view (for example, 'Breakpoints') and back fixes 'Variables' view.
Issue is reproduced in MacOS and Win8 environments.

**Comment by SlimerDude** [comment] 2016-07-14 12:37
I've seen this a few times myself on Win7.

As you mention, switching to `Breakpoints` and back to `Variables` shows the variables as you'd expect.

Scala eclipse IDE seems to have the [same problem](https://app.assembla.com/spaces/scala-ide/support/tickets/1002668-debugger-often-fails-to-retrieve-value-from-debugee-machine-%28error-code-35%29) and [StackOverflow](http://stackoverflow.com/search?q=reply%3A35) doesn't shed much light.

I wouldn't know where to begin fixing this error!

**Comment by SlimerDude** [comment] 2016-07-14 21:00
I played around a bit and noticed that the name of the class makes a difference. For example, renaming the class to `Example` and putting a breakpoint on `(2)`, it works okay!?

    class Example {
        Void main() {
            Int v := 1;
            Int v2 := v + 1;  // (2)
        }
    }

**Comment by martianov** [comment] 2016-07-16 08:21
No, when I start debugging of Example class right after F4 start I still see this issue:
![f4-debug-issue-example-classname](https://cloud.githubusercontent.com/assets/9569740/16893646/6ccb5354-4b60-11e6-9eb7-d1904550ded6.png)

**Comment by martianov** [comment] 2016-07-16 08:34
During my investigation I noticed next regularity:
**'Variables' view breaks if breakpoint is set before variable declaration.**

Please see screenshot below:
![f4-debug-issue-bp-before-declr](https://cloud.githubusercontent.com/assets/9569740/16893686/a9e28874-4b61-11e6-9d18-03065fc83121.png)
It seems like F4 failed to show content of rows of 'undeclared' variables. But user can select these rows. Number of 'empty' rows is the same as number of 'undeclared' variables.

I think we need to dig into this way..

**Comment by SlimerDude** [comment] 2016-07-25 10:23
I've just checked the history and nothing has changed in `com.xored.f4.debug` or `com.xored.f4.debug.ui` so I suspect the problem may lie elsewhere.

**Comment by SlimerDude** [comment] 2016-07-26 13:34
I believe this issue is caused by **Java v1.8**.

If you set the project's JRE to **Java 1.7** or **java 1.6** then all works fine, as per this screenshot (note how the unset variables default to `0`):

![f4-110-debug](https://cloud.githubusercontent.com/assets/3326741/17139663/4ff3bdfe-533d-11e6-8a23-bc3a84998177.png)

Moreover, I've just downloaded the old F4 1.0.2 from the Xored website and tried running the same test by setting the project's JRE to **Java 1.8**, and yep, the same error rears its ugly head:

![f4-102-debug](https://cloud.githubusercontent.com/assets/3326741/17139737/96e7e870-533d-11e6-9806-2ef0d7e2974d.png)

**Comment by SlimerDude** [comment] 2016-07-26 13:42
As I doubt we can fix this issue, I vote we document it, close it, and get on the with F4 1.1.0 release!

**Closed** 2024-06-09 11:47 UTC
Labels: can't fix
